### ISSUE TITLE
Eliminate the need for an autoloader (`services.yml`) to know about the Internal layer

### ISSUE THREAD

**Issue by TravisCarden** [php-tuf/composer-stager#268]
It is currently necessary for a client's autoloader configuration (`services.yml`) to know about Composer Stager's Internal layer. See https://github.com/php-tuf/composer-stager-console/blob/7bd5363f8c920886e855a48106163ac8afdedc14/config/services.yml#L22-L29, for example:

```yaml
services:
    PhpTuf\ComposerStager\API\FileSyncer\Service\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\Internal\FileSyncer\Factory\FileSyncerFactory', 'create' ]
    PhpTuf\ComposerStager\Internal\FileSyncer\Factory\FileSyncerFactory:
        arguments:
            $phpFileSyncer: '@PhpTuf\ComposerStager\Internal\FileSyncer\Service\PhpFileSyncer'
            $rsyncFileSyncer: '@PhpTuf\ComposerStager\Internal\FileSyncer\Service\RsyncFileSyncer'
    PhpTuf\ComposerStager\Internal\FileSyncer\Service\PhpFileSyncer: ~
    PhpTuf\ComposerStager\Internal\FileSyncer\Service\RsyncFileSyncer: ~
```

Without these, Symfony explodes:

```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service
"PhpTuf\ComposerStager\Internal\Core\Beginner": argument "$fileSyncer" of method "__construct()" references interface
"PhpTuf\ComposerStager\API\FileSyncer\Service\FileSyncerInterface" but no such service exists. You should maybe alias
this interface to one of these existing services: "PhpTuf\ComposerStager\Internal\FileSyncer\Service\PhpFileSyncer",
"PhpTuf\ComposerStager\Internal\FileSyncer\Service\RsyncFileSyncer". in
/var/www/composer-stager-console/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:49
```

This dependency needs to be eliminated or the Internal layer isn't truly internal, i.e., changes to it require clients to make corresponding change.

@phenaproxima, you said you might be able to help with this.

**Note to self:** Remember to re-enable the corresponding new PHPStan rule to prevent regressions: https://github.com/php-tuf/composer-stager/blob/e9e6cf6386edf56d4da5201d2fb84e26929931af/phpstan.neon.dist#L59-L63
